<Project Sdk="Microsoft.NET.Sdk">

  <!-- Aetheria.Engine : moteur de jeu maison (rendu, ECS, physique, input, boucle de jeu). -->

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Aetheria.Engine</RootNamespace>
    <AssemblyName>Aetheria.Engine</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
  </ItemGroup>

</Project>
