// <auto-generated />
using System;
using Aetheria.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aetheria.Database.Migrations
{
    [DbContext(typeof(AetheriaDbContext))]
    partial class AetheriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aetheria.Database.Entities.AchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UnlockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.AuctionListingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AuctionEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentBid")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CurrentBidderCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentBidderName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAuction")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ListedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PricePerUnit")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SellerCharacterId");

                    b.ToTable("AuctionListings");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.BannedIpEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("BannedIps");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.ChallengeProgressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BaselineValue")
                        .HasColumnType("bigint");

                    b.Property<string>("ChallengeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("boolean");

                    b.Property<string>("PeriodBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "ChallengeKey", "PeriodBucket")
                        .IsUnique();

                    b.ToTable("ChallengeProgress");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessoryIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ActiveMountKey")
                        .HasColumnType("text");

                    b.Property<string>("ActiveTitle")
                        .HasColumnType("text");

                    b.Property<string>("ActiveWingKey")
                        .HasColumnType("text");

                    b.Property<bool>("BattlePassHasPremium")
                        .HasColumnType("boolean");

                    b.Property<int>("BattlePassLastPremiumRewardLevel")
                        .HasColumnType("integer");

                    b.Property<int>("BattlePassLevel")
                        .HasColumnType("integer");

                    b.Property<long>("BattlePassXp")
                        .HasColumnType("bigint");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClothesColorIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GoldBoostExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HairColorIndex")
                        .HasColumnType("integer");

                    b.Property<int>("HairStyleIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Kingdom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastPositionX")
                        .HasColumnType("integer");

                    b.Property<int>("LastPositionY")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LuckBoostExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextBreedAllowedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PendingBreedCompletesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PendingBreedOffspringPassiveTalent")
                        .HasColumnType("text");

                    b.Property<int?>("PendingBreedOffspringSpeciesId")
                        .HasColumnType("integer");

                    b.Property<int?>("PendingBreedOffspringVariant")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PendingBreedParentId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PendingBreedParentId2")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PendingFusionCompletesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PendingFusionConsumedId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PendingFusionSurvivorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShowcaseItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SkinColorIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("XpBoostExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterProfessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastGatheredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "Profession")
                        .IsUnique();

                    b.ToTable("CharacterProfessions");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterQuestProgressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("QuestId");

                    b.ToTable("CharacterQuestProgress");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterTitleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterTitles");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CollectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CollectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.DungeonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHardcore")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMythic")
                        .HasColumnType("boolean");

                    b.Property<int>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMonsterLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("MythicModifierDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PositionHourBucket")
                        .HasColumnType("bigint");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<int>("WorldX")
                        .HasColumnType("integer");

                    b.Property<int>("WorldY")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.DungeonLivesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DungeonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastResetUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LivesRemaining")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "DungeonId")
                        .IsUnique();

                    b.ToTable("DungeonLives");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.FriendshipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequesterCharacterId");

                    b.HasIndex("TargetCharacterId");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.GuildChestItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildChestItems");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.GuildEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildExperience")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .HasColumnType("text");

                    b.Property<Guid>("LeaderCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TreasuryGold")
                        .HasColumnType("bigint");

                    b.Property<long>("WarPoints")
                        .HasColumnType("bigint");

                    b.Property<bool>("WeeklyQuestCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("WeeklyQuestItemsDeposited")
                        .HasColumnType("integer");

                    b.Property<string>("WeeklyQuestWeekBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeaderCharacterId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.GuildMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.InventoryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Aetheria.Database.Entities.ItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsObtainable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxStackSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RestrictedToMonsterType")
                        .HasColumnType("integer");

                    b.Property<int>("StatBonusAttack")
                        .HasColumnType("integer");

                    b.Property<int>("StatBonusDefense")
                        .HasColumnType("integer");

                    b.Property<int>("StatBonusHealth")
                        .HasColumnType("integer");

                    b.Property<int>("StatBonusIntelligence")
                        .HasColumnType("integer");

                    b.Property<int>("StatBonusResistance")
                        .HasColumnType("integer");

                    b.Property<int>("StatBonusSpeed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.KingdomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusTerritoryCount")
                        .HasColumnType("integer");

                    b.Property<string>("CapitalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("KingCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TreasuryGold")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WarPoints")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Kingdoms");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.KingdomVoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<Guid>("VoterCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId", "VoterCharacterId")
                        .IsUnique();

                    b.ToTable("KingdomVotes");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.LeaderboardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Category", "Score");

                    b.ToTable("Leaderboard");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.MonsterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EquippedAccessoryItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquippedArmorItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("EquippedWeaponItemId")
                        .HasColumnType("integer");

                    b.Property<int>("EvAttack")
                        .HasColumnType("integer");

                    b.Property<int>("EvDefense")
                        .HasColumnType("integer");

                    b.Property<int>("EvHealth")
                        .HasColumnType("integer");

                    b.Property<int>("EvIntelligence")
                        .HasColumnType("integer");

                    b.Property<int>("EvResistance")
                        .HasColumnType("integer");

                    b.Property<int>("EvSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInActiveTeam")
                        .HasColumnType("boolean");

                    b.Property<int>("IvAttack")
                        .HasColumnType("integer");

                    b.Property<int>("IvDefense")
                        .HasColumnType("integer");

                    b.Property<int>("IvHealth")
                        .HasColumnType("integer");

                    b.Property<int>("IvIntelligence")
                        .HasColumnType("integer");

                    b.Property<int>("IvResistance")
                        .HasColumnType("integer");

                    b.Property<int>("IvSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PassiveTalent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrestAttack")
                        .HasColumnType("integer");

                    b.Property<int>("PrestDefense")
                        .HasColumnType("integer");

                    b.Property<int>("PrestHealth")
                        .HasColumnType("integer");

                    b.Property<int>("PrestIntelligence")
                        .HasColumnType("integer");

                    b.Property<int>("PrestResistance")
                        .HasColumnType("integer");

                    b.Property<int>("PrestSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerCharacterId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.MonsterSpeciesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<int>("BaseIntelligence")
                        .HasColumnType("integer");

                    b.Property<string>("BaseRarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseResistance")
                        .HasColumnType("integer");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer");

                    b.Property<bool>("BreedingOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("DungeonOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Element")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvolutionLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("EvolvesIntoSpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("Habitat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCosmetic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("boolean");

                    b.Property<string>("Lore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MonsterSpecies");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.PartyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LeaderCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("LeaderCharacterId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.PartyMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("PartyId");

                    b.ToTable("PartyMembers");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.QuestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RewardExperience")
                        .HasColumnType("bigint");

                    b.Property<long>("RewardGold")
                        .HasColumnType("bigint");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ResultItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ResultQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResultItemId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.RecipeIngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.ReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportedCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReportedCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReporterCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReporterCharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Resolved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.SeasonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.StatisticsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.TerritoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ControllingKingdomId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TerritoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ControllingKingdomId");

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<int>("CharacterSlotTier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Gems")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastKnownIp")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PremiumGradeTier")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.WeeklyChestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClaimedByCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimedByCharacterName")
                        .HasColumnType("text");

                    b.Property<int>("KingdomId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<long>("RewardGold")
                        .HasColumnType("bigint");

                    b.Property<string>("WeekBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KingdomId", "WeekBucket")
                        .IsUnique();

                    b.ToTable("WeeklyChests");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.WorldBossDamageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldBossId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldBossId");

                    b.ToTable("WorldBossDamageEntries");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.WorldBossEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BossElement")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHealth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("KilledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KillerCharacterName")
                        .HasColumnType("text");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SpawnedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKingdom")
                        .HasColumnType("text");

                    b.Property<int?>("WinningKingdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorldBosses");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.AchievementEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.AuctionListingEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "SellerCharacter")
                        .WithMany()
                        .HasForeignKey("SellerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SellerCharacter");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.ChallengeProgressEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.UserEntity", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterProfessionEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterQuestProgressEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.QuestEntity", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterTitleEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany("Titles")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CollectionEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.DungeonEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.KingdomEntity", "Kingdom")
                        .WithMany()
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.FriendshipEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "RequesterCharacter")
                        .WithMany()
                        .HasForeignKey("RequesterCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "TargetCharacter")
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequesterCharacter");

                    b.Navigation("TargetCharacter");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.GuildChestItemEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.GuildEntity", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.GuildEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "LeaderCharacter")
                        .WithMany()
                        .HasForeignKey("LeaderCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaderCharacter");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.GuildMemberEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.GuildEntity", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.InventoryItemEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.KingdomVoteEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.KingdomEntity", "Kingdom")
                        .WithMany()
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.LeaderboardEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.MonsterEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "OwnerCharacter")
                        .WithMany("Monsters")
                        .HasForeignKey("OwnerCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerCharacter");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.PartyEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "LeaderCharacter")
                        .WithMany()
                        .HasForeignKey("LeaderCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeaderCharacter");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.PartyMemberEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.PartyEntity", "Party")
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.RecipeEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.ItemEntity", "ResultItem")
                        .WithMany()
                        .HasForeignKey("ResultItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultItem");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.RecipeIngredientEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.ItemEntity", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aetheria.Database.Entities.RecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.StatisticsEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.CharacterEntity", "Character")
                        .WithOne("Statistics")
                        .HasForeignKey("Aetheria.Database.Entities.StatisticsEntity", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Aetheria.Database.Entities.Statistics.CombatStatistics", "Combat", b1 =>
                        {
                            b1.Property<Guid>("StatisticsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BossesDefeated")
                                .HasColumnType("integer");

                            b1.Property<int>("CriticalHits")
                                .HasColumnType("integer");

                            b1.Property<long>("DamageDealt")
                                .HasColumnType("bigint");

                            b1.Property<long>("DamageTaken")
                                .HasColumnType("bigint");

                            b1.Property<int>("DungeonsCompleted")
                                .HasColumnType("integer");

                            b1.Property<int>("FightsLost")
                                .HasColumnType("integer");

                            b1.Property<int>("FightsWon")
                                .HasColumnType("integer");

                            b1.Property<long>("HealingDone")
                                .HasColumnType("bigint");

                            b1.Property<int>("MaxFloorReached")
                                .HasColumnType("integer");

                            b1.HasKey("StatisticsEntityId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticsEntityId");
                        });

                    b.OwnsOne("Aetheria.Database.Entities.Statistics.EconomyStatistics", "Economy", b1 =>
                        {
                            b1.Property<Guid>("StatisticsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("GoldEarned")
                                .HasColumnType("bigint");

                            b1.Property<long>("GoldSpent")
                                .HasColumnType("bigint");

                            b1.Property<int>("ItemsBought")
                                .HasColumnType("integer");

                            b1.Property<int>("ItemsCrafted")
                                .HasColumnType("integer");

                            b1.Property<int>("ItemsSold")
                                .HasColumnType("integer");

                            b1.Property<int>("TradesCompleted")
                                .HasColumnType("integer");

                            b1.HasKey("StatisticsEntityId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticsEntityId");
                        });

                    b.OwnsOne("Aetheria.Database.Entities.Statistics.ExplorationStatistics", "Exploration", b1 =>
                        {
                            b1.Property<Guid>("StatisticsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ChestsOpened")
                                .HasColumnType("integer");

                            b1.Property<int>("DeepestFloorReached")
                                .HasColumnType("integer");

                            b1.Property<int>("DungeonsVisited")
                                .HasColumnType("integer");

                            b1.Property<int>("MapsDiscovered")
                                .HasColumnType("integer");

                            b1.Property<int>("SecretsFound")
                                .HasColumnType("integer");

                            b1.Property<int>("TeleportersUnlocked")
                                .HasColumnType("integer");

                            b1.HasKey("StatisticsEntityId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticsEntityId");
                        });

                    b.OwnsOne("Aetheria.Database.Entities.Statistics.MonsterStatistics", "Monsters", b1 =>
                        {
                            b1.Property<Guid>("StatisticsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EvolutionsPerformed")
                                .HasColumnType("integer");

                            b1.Property<int>("LegendariesObtained")
                                .HasColumnType("integer");

                            b1.Property<int>("MonstersCaptured")
                                .HasColumnType("integer");

                            b1.Property<int>("ShiniesFound")
                                .HasColumnType("integer");

                            b1.Property<int>("SpeciesDiscovered")
                                .HasColumnType("integer");

                            b1.HasKey("StatisticsEntityId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticsEntityId");
                        });

                    b.OwnsOne("Aetheria.Database.Entities.Statistics.PvpStatistics", "Pvp", b1 =>
                        {
                            b1.Property<Guid>("StatisticsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("BestRank")
                                .HasColumnType("integer");

                            b1.Property<int>("CurrentRank")
                                .HasColumnType("integer");

                            b1.Property<int>("Losses")
                                .HasColumnType("integer");

                            b1.Property<int>("Season")
                                .HasColumnType("integer");

                            b1.Property<int>("WinStreak")
                                .HasColumnType("integer");

                            b1.Property<int>("Wins")
                                .HasColumnType("integer");

                            b1.HasKey("StatisticsEntityId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticsEntityId");
                        });

                    b.OwnsOne("Aetheria.Database.Entities.Statistics.SocialStatistics", "Social", b1 =>
                        {
                            b1.Property<Guid>("StatisticsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("FriendsCount")
                                .HasColumnType("integer");

                            b1.Property<int>("MessagesSent")
                                .HasColumnType("integer");

                            b1.Property<long>("PlayTimeSeconds")
                                .HasColumnType("bigint");

                            b1.Property<int>("PlayersHelped")
                                .HasColumnType("integer");

                            b1.HasKey("StatisticsEntityId");

                            b1.ToTable("Statistics");

                            b1.WithOwner()
                                .HasForeignKey("StatisticsEntityId");
                        });

                    b.Navigation("Character");

                    b.Navigation("Combat")
                        .IsRequired();

                    b.Navigation("Economy")
                        .IsRequired();

                    b.Navigation("Exploration")
                        .IsRequired();

                    b.Navigation("Monsters")
                        .IsRequired();

                    b.Navigation("Pvp")
                        .IsRequired();

                    b.Navigation("Social")
                        .IsRequired();
                });

            modelBuilder.Entity("Aetheria.Database.Entities.TerritoryEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.KingdomEntity", "ControllingKingdom")
                        .WithMany()
                        .HasForeignKey("ControllingKingdomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ControllingKingdom");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.WeeklyChestEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.KingdomEntity", "Kingdom")
                        .WithMany()
                        .HasForeignKey("KingdomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kingdom");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.WorldBossDamageEntity", b =>
                {
                    b.HasOne("Aetheria.Database.Entities.WorldBossEntity", "WorldBoss")
                        .WithMany("DamageEntries")
                        .HasForeignKey("WorldBossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorldBoss");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.CharacterEntity", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Monsters");

                    b.Navigation("Statistics");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.RecipeEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.UserEntity", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Aetheria.Database.Entities.WorldBossEntity", b =>
                {
                    b.Navigation("DamageEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
